spring:
  h2:
    console:
      enable: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always #data.sql 찾아감.
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: root
